// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/da1c32084c97d7aea0369a7f5dbe9cb954c8e3b6/empower/empower.d.ts
declare function empower(originalAssert:any, formatter:any, options?:empower.Options):any;

declare namespace empower {
    export interface Options {
        destructive?: boolean;
        modifyMessageOnRethrow?: boolean;
        saveContextOnRethrow?: boolean;
        patterns?: string[];
    }
}

declare module "empower" {
    export = empower;
}
